### ISSUE TITLE
Develop a Fiori App Using ABAP

### ISSUE THREAD

**Issue by tpembe** [SAPDocuments/Tutorials#4173]
Mission URL: https://developers.sap.com/mission.cp-starter-extensions-abap.html

I completed this mission yesterday! Strangely now all the completion history has been reset. If I try to complete a 2nd time by clicking the button, the browser returns the cursor to the top of the html page. I though the purpose of these missions were they provide you with training history on your profile. If they dont it would be useful if they did so you can view history of topics completed.

Thanks
Troy

**Comment by thecodester** [comment]
Can you check again. I think there was a general problem but it should be working now.

**Comment by tpembe** [comment]
![fioriappstatus](https://user-images.githubusercontent.com/17800562/68550369-1a873f80-03fa-11ea-90cc-5f5232a1115b.PNG)

Still showing as 83% even though mission has been completed.

**Comment by tpembe** [comment]
#4179

**Comment by thecodester** [comment]
I am checking. What is your name? I want to check if I see you've been credited with doing the mission and the issue is on the display.

I have closed the related issue.

**Comment by tpembe** [comment]
My name is Troy Pemberton my account troypemberton@greenplains.co.uk

**Comment by tpembe** [comment]
It still shows as 83%

**Comment by thecodester** [comment]
Can you check again tomorrow morning and post if you have the mission completed?

**Comment by tpembe** [comment]
Issue fixed
