### ISSUE TITLE
Set Up Process Visibility to Track Employee Onboarding Workflow

### ISSUE THREAD

**Issue by NidhiMurkute** [SAPDocuments/Tutorials#5674]
Tutorial URL: https://developers.sap.com/tutorials/cp-starter-ibpm-employeeonboarding-4-visibility.html

Please specify the step you are referring to: Step 5: Activate the business scenario     
Configured the properties as mentioned in tutorial but it displays invalid entry for Event A and Event B. Although after click on Activate the error goes off but since after selecting the Event A and Event B, the invalid entry error mislead the user.
![image](https://user-images.githubusercontent.com/50734023/89868534-95bb9300-dbd0-11ea-949b-93fcc5c626da.png)

Regards,
Nidhi

**Comment by ArchanaShukla** [comment]
This is the minor product issue known and should be fixed in upcoming release.
@thecodester - Close the issue.

**Comment by ArchanaShukla** [comment]
This issue wont be fixed. It appears sporadicly and is not reproducible anymore!

**Comment by i353590** [comment]
Hello,

We have executed the scenario recently, the issue still persists.
It is still not fixed.

Could you please check again.?

Thanks,
Shubham
